export { apiClient, ApiClient, type RequestOptions } from './client.ts'
export { clearApiKey, getApiBaseUrl, getApiKey, setApiKey } from './config.ts'
export {
  ApiError,
  BadRequestError,
  isApiError,
  isBadRequestError,
  isNotFoundError,
  isUnauthorizedError,
  isValidationError,
  NotFoundError,
  UnauthorizedError,
  ValidationError,
  type ValidationDetail,
} from './errors.ts'
export { mailingsApi, meApi, providersApi, statsApi, templatesApi } from './endpoints.ts'
export type {
  ApiDetailError,
  MailingCreate,
  MailingCreateMessage,
  MailingListParams,
  MailingRead,
  MailingStatus,
  MailingTemplateCreate,
  MailingTemplateRead,
  MailingTemplateUpdate,
  MessageRead,
  MessageStatus,
  MessagesByProviderStatsItem,
  MessagesByProviderStatsParams,
  MessagesByProviderStatsResponse,
  Page,
  ProviderListResponse,
  ProviderRead,
  ProviderListParams,
  ProviderUpdate,
  SendMailingResponse,
  TemplateListParams,
  UserRead,
} from './types.ts'
