export { localizeConflictDetail } from "./conflict-messages.ts";
export { apiClient, ApiClient, type RequestOptions } from "./client.ts";
export {
  clearCredentials,
  getApiBaseUrl,
  getCredentials,
  setCredentials,
} from "./config.ts";
export {
  ApiError,
  BadRequestError,
  ConflictError,
  ForbiddenError,
  isApiError,
  isBadRequestError,
  isConflictError,
  isForbiddenError,
  isNotFoundError,
  isUnauthorizedError,
  isValidationError,
  NotFoundError,
  UnauthorizedError,
  ValidationError,
  type ValidationDetail,
} from "./errors.ts";
export {
  mailingsApi,
  messagesApi,
  meApi,
  providersApi,
  servicesApi,
  statsApi,
  templatesApi,
  usersApi,
} from "./endpoints.ts";
export type {
  ApiDetailError,
  BasicCredentials,
  MailingCreate,
  MailingCreateMessage,
  MailingListParams,
  MailingRead,
  MailingStatus,
  MailingTemplateCreate,
  MailingTemplateRead,
  MailingTemplateUpdate,
  MessageRead,
  MailingUpdate,
  MessageStatus,
  MessagesByProviderStatsItem,
  MessagesByProviderStatsParams,
  MessagesByProviderStatsResponse,
  Page,
  ProviderListResponse,
  ProviderRead,
  ProviderListParams,
  ProviderUpdate,
  SendMailingResponse,
  TemplateListParams,
  UserCreate,
  UserListParams,
  UserRead,
  UserRole,
  UserUpdate,
  SmsTextAnalyzeRequest,
  SmsTextAnalyzeResponse,
  SmsMessageEncoding,
} from "./types.ts";

export { MESSAGE_STATUS_LABELS } from "./types.ts";
