export { localizeConflictDetail } from "./conflict-messages.ts";
export { apiClient, ApiClient, type RequestOptions } from "./client.ts";
export { clearApiKey, getApiBaseUrl, getApiKey, setApiKey } from "./config.ts";
export {
  ApiError,
  BadRequestError,
  ConflictError,
  isApiError,
  isBadRequestError,
  isConflictError,
  isNotFoundError,
  isUnauthorizedError,
  isValidationError,
  NotFoundError,
  UnauthorizedError,
  ValidationError,
  type ValidationDetail,
} from "./errors.ts";
export {
  mailingsApi,
  messagesApi,
  meApi,
  providersApi,
  servicesApi,
  statsApi,
  templatesApi,
} from "./endpoints.ts";
export type {
  ApiDetailError,
  MailingCreate,
  MailingCreateMessage,
  MailingListParams,
  MailingRead,
  MailingStatus,
  MailingTemplateCreate,
  MailingTemplateRead,
  MailingTemplateUpdate,
  MessageRead,
  MailingUpdate,
  MessageStatus,
  MessagesByProviderStatsItem,
  MessagesByProviderStatsParams,
  MessagesByProviderStatsResponse,
  Page,
  ProviderListResponse,
  ProviderRead,
  ProviderListParams,
  ProviderUpdate,
  SendMailingResponse,
  TemplateListParams,
  UserRead,
  SmsTextAnalyzeRequest,
  SmsTextAnalyzeResponse,
  SmsMessageEncoding,
} from "./types.ts";
